// Pre-consultation summaries. Priya's is hand-written (scripts.ts §11.1); for other consults
// the same structure is assembled from clinic records. Nothing is generated by a model.

import type { Appointment, Patient } from '@/data/types';
import { HERO_IDS } from '@/data/heroes';
import { PRIYA_SUMMARY, type AiSummary, type SummaryLine } from '@/data/scripts';
import { fmtDate, fmtDay, fmtMonth, daysSince } from './dates';
import { storedEmbryos } from './selectors';

const d = (s?: string) => (s ? `${fmtDay(s)} ${s.slice(0, 4)}` : undefined);

export function summaryFor(p: Patient, a: Appointment): AiSummary {
  if (p.id === HERO_IDS.priya) return PRIYA_SUMMARY;
  const c = p.clinical;
  const lab = d(c.labDate);

  const background: SummaryLine[] = [];
  if (c.diagnosis[0] !== 'Not yet assessed') background.push({ text: `${c.diagnosis.join('; ')}.`, chips: [{ source: 'EMR' }] });
  if (c.amh !== undefined) background.push({ text: `AMH ${c.amh} ng/mL${c.afc !== undefined ? `, AFC ${c.afc}` : ''}${c.amh < 1.2 ? ' (low ovarian reserve)' : ''}.`, chips: [{ source: 'Lab', date: lab }] });
  if (c.tsh !== undefined) background.push({ text: `TSH ${c.tsh} mIU/L${c.tsh > 4 ? ', raised' : ''}. BMI ${c.bmi}.`, chips: [{ source: 'Lab', date: lab }] });
  if (c.semen) background.push({ text: `Semen: concentration ${c.semen.concentration} M/mL, progressive motility ${c.semen.progressiveMotility}%, normal morphology ${c.semen.morphology}%.`, chips: [{ source: 'Lab', date: lab }] });
  if (!background.length) background.push({ text: `${p.age} years. ${c.type} infertility, ${c.infertilityYears} years. No investigations on file yet.`, chips: [{ source: 'EMR' }] });

  const treatment: SummaryLine[] = p.cycles.map((cy) => {
    if (cy.type === 'FET') return { text: `${fmtMonth(cy.startOn)}: ${cy.protocol}, ${cy.blastocysts?.[0] ? `day-${cy.blastocysts[0].day} blastocyst (${cy.blastocysts[0].grade}) transferred` : 'transfer'}${cy.endometriumMm ? `, endometrium ${cy.endometriumMm} mm` : ''}.${cy.betaValue !== undefined ? ` Beta hCG ${cy.betaValue} mIU/mL.` : ''}`, chips: [{ source: 'IVF software' }] };
    if (cy.type === 'FERTILITY_PRESERVATION') return { text: `${fmtMonth(cy.startOn)}: oocyte freezing, ${cy.mii} MII oocytes vitrified.`, chips: [{ source: 'IVF software' }] };
    if (!cy.opuOn) return { text: `Current cycle: ${cy.protocol}, stimulation day ${cy.stimDays}. ${cy.note ?? ''}`.trim(), chips: [{ source: 'IVF software' }, { source: 'EMR', date: 'today' }] };
    return { text: `${fmtMonth(cy.startOn)}: ${cy.protocol.toLowerCase()} ICSI, ${cy.stimDays} stimulation days. ${cy.oocytes ?? '—'} oocytes, ${cy.mii ?? '—'} MII, ${cy.fertilised2PN ?? '—'} fertilised.${cy.blastocysts ? ` ${cy.blastocysts.length} blastocyst${cy.blastocysts.length === 1 ? '' : 's'}.` : ''}`, chips: [{ source: 'IVF software' }] };
  });

  const sections: AiSummary['sections'] = [{ heading: 'Background', lines: background }];
  if (treatment.length) sections.push({ heading: 'Treatment so far', lines: treatment });
  const emb = storedEmbryos(p);
  if (emb) {
    const item = p.cryo.find((x) => x.kind === 'Embryo')!;
    sections.push({ heading: 'In storage', lines: [{ text: `${emb} vitrified blastocyst${emb === 1 ? '' : 's'} (${item.grade}), frozen ${fmtDate(item.frozenOn)}. ${item.tank}, Canister ${item.canister}, Cane ${item.cane}.`, chips: [{ source: 'Cryo register' }] }] });
  }
  const since: SummaryLine[] = [{ text: `In ${p.stage === 'enquiry' ? 'enquiry' : 'the current stage'} for ${daysSince(p.stageEnteredOn)} days.${p.lastContactOn ? ` Last contact ${fmtDate(p.lastContactOn)}.` : ''}`, chips: [{ source: 'Anvaya' }] }];
  if (p.financial.emi) since.push({ text: 'Asked about EMI options.', chips: [{ source: 'Billing' }] });
  if (p.wellbeing?.band && p.wellbeing.band !== 'Low') since.push({ text: `Wellbeing screen: ${p.wellbeing.band.toLowerCase()} (${p.wellbeing.score} of 30).`, chips: [{ source: 'Anvaya', date: d(p.wellbeing.lastScreenOn) }] });
  sections.push({ heading: 'Since the last visit', lines: since });

  // Points to discuss come from the brief, phrased as prompts, never decisions
  const points = a.brief
    .split(/[.;]\s*/)
    .map((s) => s.trim())
    .filter((s) => /^(Discuss|Consider|Plan|Asked|Wellbeing|Consent|Mild)/i.test(s));
  sections.push({ heading: 'Points to discuss', lines: (points.length ? points : ['Review findings and agree next steps with the couple']).map((t) => ({ text: t.endsWith('.') ? t : `${t}.`, chips: [] })) });

  return {
    title: `${a.visitType} — ${p.name} (${p.age})${p.partner ? ` and ${p.partner.name} (${p.partner.age})` : ''}`,
    subtitle: `${c.infertilityYears ? `${c.type} infertility, ${c.infertilityYears} years. ` : ''}${p.referrerName ? `Referred by ${p.referrerName}.` : `Source: ${p.referralSource}.`}`,
    sections,
  };
}

export function summaryAsText(s: AiSummary): string {
  return [s.title, s.subtitle, '', ...s.sections.flatMap((sec) => [sec.heading, ...sec.lines.map((l) => `- ${l.text}`), ''])].join('\n');
}
